import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import { useRouter } from 'next/router'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

const router = useRouter();

  const [formData, setFormData] = useState({
    firstName:'',
    userName:''
  })

  const CheckLogin =() => {
    console.log(formData.firstName)
    console.log(formData)

    if(formData.username !== null){
      router.push({
        pathname: './counter',
        query: {
          username: formData.username
        }
      })
    }
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <div className={styles.loginBox}>
        <label>First Name: </label>
        <input
          type="text"
          id="first"
          name="first"
          pattern="[A-Z]{1}[a-z]{2-10}"
          title='the first letter should be capital'
          onChange={(e=> setFormData({...formData, firstName: e.target.value}))}
        />

        <label>User Name: </label>
        <input
          type="text"
          id="username"
          name="username"
          required 
          title='the first letter should be capital'
          maxLength="10"
          minlength="5"
          onChange={(e=> setFormData({...formData, username: e.target.value}))}
        />
        <button className={styles.button} type="submit" onClick={() => CheckLogin()}>Submit</button>

        </div>
      </main>
    </>
  )
}
